
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ivolve-app
  namespace: ivolve
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ivolve-app
  template:
    metadata:
      labels:
        app: ivolve-app
    spec:
      containers:
      - name: ivolve-container
        image: yasminsalah321/ivolve-node-app:latest
        ports:
        - containerPort: 3000

